spring:
  application:
    name: web-socket

  liquibase:
    change-log: classpath:database/liquibase-changelog.yml
    url: \${DATABASE_URL:jdbc:postgresql://localhost:5432/web-socket}
    user: \${DATABASE_USERNAME:postgres}
    password: \${DATABASE_PASSWORD:postgres}
    enabled: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: \${DATABASE_URL:jdbc:postgresql://localhost:5432/web-socket}
    username: \${DATABASE_USERNAME:postgres}
    password: \${DATABASE_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false
    defer-datasource-initialization: false

  sql:
    init:
      mode: never

  output:
    ansi:
      enabled: always

app:
  version: ${version}
  name: \${spring.application.name}
  description: ${description}

server:
  port: 8090
  servlet:
    context-path: \${CONTEXT_PATH:/}

springdoc:
  swagger-ui:
    doc-expansion: none

cors-configuration:
  origins: [ "*" ]
  methods: [ "*" ]
  headers: [ "*" ]
  credentials: false
  max-age: 3600